site_name: oligo Docs

repo_url: https://github.com/iOLIGO/oligo

theme: material

nav:
  - Home: index.md
  - Oligo Usage: oligo.md
  - Oligo5 Usage: oligo5.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
