site_name: oligo Docs

repo_url: https://github.com/iOLIGO/oligo

theme: material

nav:
  - Home: index.md
  - Basic Usage: basic_usage.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
